version: "3.1"

services:
  mysql:
    container_name: openai_test
    image: mysql:8.1
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: openai_test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - openai_test
volumes:
  mysql:
networks:
  openai_test:
